import { supabase } from "@/integrations/supabase/client";

const sb = supabase as any;

export interface CreateInvoiceResult {
  ok: boolean;
  created: string[];          // invoice numbers created
  skippedExisting: number;    // customers already invoiced for this dispatch
  skippedNoCustomer: number;  // items with no resolvable customer
  error?: string;
}

/**
 * Auto-create the domestic sales invoice(s) for a dispatch.
 *
 * Every domestic dispatch must produce an invoice. A dispatch can span more than
 * one customer (its items chain back to different orders/customers), so we group
 * the dispatch items by customer and create one draft invoice per customer.
 *
 * Idempotent: a customer already invoiced for this dispatch is skipped, so this
 * is safe to call again (and never duplicates the manual "New Invoice" flow).
 * Non-throwing — returns a result the caller can surface as a toast.
 */
export async function createInvoiceForDispatch(
  dispatchId: string,
  opts: { createdBy?: string | null; paymentTerms?: string } = {},
): Promise<CreateInvoiceResult> {
  try {
    const paymentTerms = opts.paymentTerms || "Net 30";
    const today = new Date();
    const invoiceDate = today.toISOString().slice(0, 10);
    const netDays = parseInt(paymentTerms.match(/Net (\d+)/)?.[1] || "30", 10);
    const dueDate = new Date(today.getTime() + netDays * 86400000).toISOString().slice(0, 10);

    // 1) Load the dispatch items + their customer / price / product.
    const { data: items, error: iErr } = await sb
      .from("sales_dispatch_items")
      .select(
        "id, quantity_dozens, packing_type, " +
        "order_item:sales_order_items(price_per_dozen, details, product:products(id, code, name), grade:grades(name), order:sales_orders(customer:customers(id, name, code)))"
      )
      .eq("dispatch_id", dispatchId);
    if (iErr) return { ok: false, created: [], skippedExisting: 0, skippedNoCustomer: 0, error: iErr.message };
    if (!items || items.length === 0) {
      return { ok: true, created: [], skippedExisting: 0, skippedNoCustomer: 0 };
    }

    // 2) Group items by customer; drop items that don't resolve to a customer.
    const groups = new Map<string, any[]>();
    let skippedNoCustomer = 0;
    for (const it of items) {
      const customerId = it.order_item?.order?.customer?.id;
      if (!customerId) { skippedNoCustomer++; continue; }
      if (!groups.has(customerId)) groups.set(customerId, []);
      groups.get(customerId)!.push(it);
    }

    // 3) Skip customers already invoiced for this dispatch (idempotency).
    const { data: existing } = await sb
      .from("domestic_invoices")
      .select("customer_id")
      .eq("dispatch_id", dispatchId);
    const alreadyInvoiced = new Set((existing || []).map((r: any) => r.customer_id));

    const created: string[] = [];
    let skippedExisting = 0;

    for (const [customerId, groupItems] of groups) {
      if (alreadyInvoiced.has(customerId)) { skippedExisting++; continue; }

      const total = groupItems.reduce(
        (s: number, it: any) => s + Number(it.quantity_dozens || 0) * Number(it.order_item?.price_per_dozen || 0),
        0,
      );

      const { data: inv, error: invErr } = await sb
        .from("domestic_invoices")
        .insert({
          invoice_number: "", // auto-generated by trigger (INV-YYYYMM-NNNN)
          dispatch_id: dispatchId,
          customer_id: customerId,
          invoice_date: invoiceDate,
          due_date: dueDate,
          payment_terms: paymentTerms,
          subtotal: total,
          total_amount: total,
          status: "draft",
          created_by: opts.createdBy || null,
        })
        .select("id, invoice_number")
        .single();
      if (invErr) return { ok: false, created, skippedExisting, skippedNoCustomer, error: invErr.message };

      const itemsPayload = groupItems.map((it: any, i: number) => {
        const qty = Number(it.quantity_dozens || 0);
        const price = Number(it.order_item?.price_per_dozen || 0);
        const product = it.order_item?.product;
        return {
          invoice_id: inv.id,
          dispatch_item_id: it.id,
          product_id: product?.id || null,
          description: product ? `${product.code || ""} — ${product.name || ""}` : null,
          details: it.order_item?.details || null,
          grade_name: it.order_item?.grade?.name || null,
          packing_type: it.packing_type || null,
          quantity_dozens: qty,
          price_per_dozen: price,
          amount: qty * price,
          line_order: i,
        };
      });
      if (itemsPayload.length > 0) {
        const { error: liErr } = await sb.from("domestic_invoice_items").insert(itemsPayload);
        if (liErr) return { ok: false, created, skippedExisting, skippedNoCustomer, error: liErr.message };
      }

      created.push(inv.invoice_number);
    }

    return { ok: true, created, skippedExisting, skippedNoCustomer };
  } catch (e: any) {
    return { ok: false, created: [], skippedExisting: 0, skippedNoCustomer: 0, error: e?.message || String(e) };
  }
}
