// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://ojejlhnthhdvgbgpsgvi.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_maHf4XFU4sbsRHv1Z-8jgw_5qoDvpYq';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});